<a href="https://colab.research.google.com/github/MrPraphul/Casestudy_NumpyPandas/blob/main/CasestudyNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# Import pandas for data analysis
import pandas as pd

# Import numpy for numerical operations
import numpy as np

# Load the IMDB movie dataset
url ='https://raw.githubusercontent.com/laxmimerit/All-CSV-ML-Data-Files-Download/master/IMDB-Movie-Data.csv'
df = pd.read_csv(url)

# Display the first 5 rows
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [11]:
# Display number of rows and columns
print("Shape of dataset:", df.shape)

Shape of dataset: (1000, 12)

In [12]:
# Display first 5 rows
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [13]:
# Display all column names
print(df.columns)

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [14]:
# Display data type of each column
print(df.dtypes)

Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object

In [15]:
# Count missing values in each column
print(df.isnull().sum())

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [16]:
# Check the number of duplicate rows
print("Number of duplicate rows:", df.duplicated().sum())


# Remove duplicate rows
df = df.drop_duplicates()

# Check duplicates again
print("Duplicates after removal:", df.duplicated().sum())

Number of duplicate rows: 0
Duplicates after removal: 0

In [17]:
# Rename the Title column to movie title
df = df.rename(columns={"bahubali": "movie_title"})

# Display the updated column names
print(df.columns)

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [21]:
# Get all genre values
genres = df["Genre"].dropna().str.split("|").explode().unique()

# Display unique genres
print(genres)

['Action,Adventure,Sci-Fi' 'Adventure,Mystery,Sci-Fi' 'Horror,Thriller'
 'Animation,Comedy,Family' 'Action,Adventure,Fantasy' 'Comedy,Drama,Music'
 'Comedy' 'Action,Adventure,Biography' 'Adventure,Drama,Romance'
 'Adventure,Family,Fantasy' 'Biography,Drama,History'
 'Animation,Adventure,Comedy' 'Action,Comedy,Drama' 'Action,Thriller'
 'Biography,Drama' 'Drama,Mystery,Sci-Fi' 'Adventure,Drama,Thriller'
 'Drama' 'Crime,Drama,Horror' 'Action,Adventure,Drama' 'Drama,Thriller'
 'Action,Adventure,Comedy' 'Action,Horror,Sci-Fi' 'Adventure,Drama,Sci-Fi'
 'Action,Adventure,Western' 'Comedy,Drama' 'Horror'
 'Adventure,Drama,Fantasy' 'Action,Crime,Thriller' 'Action,Crime,Drama'
 'Adventure,Drama,History' 'Crime,Horror,Thriller' 'Drama,Romance'
 'Comedy,Drama,Romance' 'Horror,Mystery,Thriller' 'Crime,Drama,Mystery'
 'Drama,Romance,Thriller' 'Drama,History,Thriller' 'Action,Drama,Thriller'
 'Drama,History' 'Action,Drama,Romance' 'Drama,Fantasy' 'Action,Sci-Fi'
 'Adventure,Drama,War' 'Action,Comedy,Fantasy' 'Biography,Comedy,Crime'
 'Crime,Drama' 'Comedy,Crime,Drama' 'Action,Comedy,Crime'
 'Animation,Drama,Fantasy' 'Horror,Mystery,Sci-Fi'
 'Drama,Mystery,Thriller' 'Crime,Drama,Thriller' 'Biography,Crime,Drama'
 'Crime,Mystery,Thriller' 'Action,Horror,Thriller' 'Romance,Sci-Fi'
 'Action,Fantasy,War' 'Action,Biography,Drama' 'Drama,Horror,Mystery'
 'Adventure,Drama,Family' 'Adventure,Comedy,Romance' 'Action'
 'Adventure,Crime,Mystery' 'Comedy,Family,Musical'
 'Adventure,Comedy,Drama' 'Drama,Horror,Thriller' 'Drama,Music'
 'Mystery,Thriller' 'Mystery,Thriller,Western' 'Comedy,Family'
 'Biography,Comedy,Drama' 'Drama,Western' 'Drama,Mystery,Romance'
 'Action,Drama,Mystery' 'Action,Adventure,Crime'
 'Adventure,Sci-Fi,Thriller' 'Action,Comedy,Mystery' 'Thriller,War'
 'Action,Adventure,Thriller' 'Drama,Fantasy,Romance'
 'Action,Drama,History' 'Animation,Adventure,Family' 'Adventure,Horror'
 'Drama,Romance,Sci-Fi' 'Action,Adventure,Family' 'Action,Comedy'
 'Comedy,Romance' 'Horror,Mystery' 'Drama,Family,Fantasy' 'Sci-Fi'
 'Drama,War' 'Drama,Fantasy,Horror' 'Crime,Drama,History'
 'Horror,Sci-Fi,Thriller' 'Action,Drama,Sport' 'Adventure,Biography,Drama'
 'Biography,Drama,Thriller' 'Action,Adventure,Mystery' 'Drama,Horror'
 'Comedy,Crime' 'Drama,Fantasy,War' 'Action,Adventure,Romance'
 'Action,Drama,War' 'Drama,Musical,Romance' 'Drama,Sci-Fi,Thriller'
 'Action,Drama,Sci-Fi' 'Drama,Sci-Fi' 'Adventure,Fantasy' 'Thriller'
 'Biography,Drama,Romance' 'Action,Adventure' 'Action,Fantasy'
 'Action,Drama,Horror' 'Comedy,Music,Romance' 'Biography,Drama,Sport'
 'Action,Horror' 'Comedy,Horror,Thriller' 'Crime,Drama,Music'
 'Action,Sci-Fi,Thriller' 'Drama,Horror,Sci-Fi' 'Drama,Sport'
 'Comedy,Horror' 'Comedy,Fantasy,Romance' 'Comedy,Fantasy'
 'Comedy,Drama,Fantasy' 'Adventure,Comedy,Horror' 'Comedy,Mystery'
 'Action,Mystery,Sci-Fi' 'Action,Crime,Fantasy' 'Comedy,Fantasy,Horror'
 'Animation,Action,Adventure' 'Action,Comedy,Family' 'Comedy,Sci-Fi'
 'Action,Biography,Crime' 'Adventure,Comedy' 'Comedy,Music'
 'Comedy,Drama,Horror' 'Action,Horror,Romance' 'Action,Drama,Fantasy'
 'Action,Mystery,Thriller' 'Action,Adventure,Horror'
 'Animation,Family,Fantasy' 'Adventure,Horror,Mystery'
 'Action,Horror,Mystery' 'Adventure,Comedy,Family' 'Action,Crime,Mystery'
 'Comedy,Drama,Family' 'Action,Crime,Sport' 'Mystery,Sci-Fi,Thriller'
 'Sci-Fi,Thriller' 'Adventure,Drama,Horror' 'Biography,History,Thriller'
 'Adventure,Comedy,Sci-Fi' 'Fantasy,Horror' 'Action,Fantasy,Thriller'
 'Comedy,Romance,Sport' 'Animation,Action,Comedy' 'Drama,Fantasy,Thriller'
 'Action,Comedy,Romance' 'Action,Fantasy,Horror' 'Mystery,Romance,Sci-Fi'
 'Comedy,Drama,Thriller' 'Comedy,Western' 'Drama,History,War'
 'Fantasy,Horror,Thriller' 'Drama,Horror,Musical' 'Drama,Family'
 'Romance,Sci-Fi,Thriller' 'Animation,Fantasy' 'Drama,Mystery,War'
 'Action,Drama,Family' 'Adventure,Drama,Western' 'Drama,Music,Romance'
 'Comedy,Romance,Western' 'Adventure,Drama' 'Drama,Thriller,War'
 'Drama,Fantasy,Mystery' 'Comedy,Crime,Thriller' 'Animation,Comedy,Drama'
 'Action,Comedy,Sci-Fi' 'Drama,Romance,War' 'Adventure,Fantasy,Mystery'
 'Mystery,Romance,Thriller' 'Biography,Drama,Mystery'
 'Animation,Drama,Romance' 'Comedy,Horror,Romance' 'Action,Thriller,War'
 'Action,Comedy,Horror' 'Action,Crime,Sci-Fi' 'Crime,Thriller'
 'Comedy,Horror,Sci-Fi' 'Crime,Drama,Fantasy' 'Drama,Fantasy,Music'
 'Action,Comedy,Sport' 'Fantasy,Mystery,Thriller' 'Adventure'
 'Adventure,Biography' 'Adventure,Biography,Crime' 'Comedy,Drama,Musical'
 'Comedy,Family,Romance' 'Biography,Drama,Family' 'Drama,Fantasy,Musical'
 'Adventure,Family' 'Adventure,Comedy,Fantasy' 'Drama,Family,Music'
 'Comedy,Family,Fantasy']

In [24]:
# Count genres in each movie
df["Genre_Count"] = df["Genre"].fillna("").str.split("|").str.len()
df[["Title", "Genre", "Genre_Count"]].head()

                     Title                     Genre  Genre_Count
0  Guardians of the Galaxy   Action,Adventure,Sci-Fi            1
1               Prometheus  Adventure,Mystery,Sci-Fi            1
2                    Split           Horror,Thriller            1
3                     Sing   Animation,Comedy,Family            1
4            Suicide Squad  Action,Adventure,Fantasy            1

In [25]:
# Check missing values
print("Missing Revenue values:")
print(df["Revenue (Millions)"].isnull().sum())

print("\nMissing Metascore values:")
print(df["Metascore"].isnull().sum())

Missing Revenue values:
128

Missing Metascore values:
64

In [26]:
# Fill missing Revenue values with the median revenue
df["Revenue (Millions)"] = df["Revenue (Millions)"].fillna(
    df["Revenue (Millions)"].median()
)

# Fill missing Metascore values with the median metascore
df["Metascore"] = df["Metascore"].fillna(
    df["Metascore"].median()
)

# Check missing values again
print(df[["Revenue (Millions)", "Metascore"]].isnull().sum())

Revenue (Millions)    0
Metascore             0
dtype: int64

In [29]:
# Sort movies by Rating from highest to lowest
top_5_movies = df.sort_values(
    by="Rating",
    ascending=False
).head(5)

# Display movie title and rating
print(top_5_movies[["Title", "Rating"]])

                Title  Rating
54    The Dark Knight     9.0
80          Inception     8.8
117            Dangal     8.8
36       Interstellar     8.6
249  The Intouchables     8.6

In [31]:
# Find the movie with the highest revenue
highest_revenue = df.loc[df["Revenue (Millions)"].idxmax()]

print("Movie with highest revenue:")
print(highest_revenue[["Title", "Revenue (Millions)"]])

Movie with highest revenue:
Title                 Star Wars: Episode VII - The Force Awakens
Revenue (Millions)                                        936.63
Name: 50, dtype: object

In [33]:
# Find the movie with the lowest revenue
lowest_revenue = df.loc[df["Revenue (Millions)"].idxmin()]

print("Movie with lowest revenue:")
print(lowest_revenue[["Title", "Revenue (Millions)"]])

Movie with lowest revenue:
Title                 A Kind of Murder
Revenue (Millions)                 0.0
Name: 231, dtype: object

In [35]:
# Calculate average rating for each director
avg_rating_director = df.groupby("Director")["Rating"].mean()

# Sort from highest to lowest
avg_rating_director = avg_rating_director.sort_values(
    ascending=False
)

# Display the result
print(avg_rating_director)

Director
Nitesh Tiwari                       8.80
Christopher Nolan                   8.68
Olivier Nakache                     8.60
Makoto Shinkai                      8.60
Florian Henckel von Donnersmarck    8.50
                                    ...
Micheal Bafaro                      3.50
Jonathan Holbrook                   3.20
Shawn Burkett                       2.70
James Wong                          2.70
Jason Friedberg                     1.90
Name: Rating, Length: 644, dtype: float64

In [37]:
# Count the number of movies released in each year
movies_per_year = df.groupby("Year")["Title"].count()

# Display the result
print(movies_per_year)

Year
2006     44
2007     53
2008     52
2009     51
2010     60
2011     63
2012     64
2013     91
2014     98
2015    127
2016    297
Name: Title, dtype: int64

In [39]:
# Filter movies having:
# Rating greater than 8
# Revenue greater than 100 million

filtered_movies = df[
    (df["Rating"] > 8) &
    (df["Revenue (Millions)"] > 100)
]

# Display the movies
print(
    filtered_movies[
        ["Title", "Rating", "Revenue (Millions)"]
    ]
)

                                            Title  Rating  Revenue (Millions)
0                         Guardians of the Galaxy     8.1              333.13
6                                      La La Land     8.3              151.06
36                                   Interstellar     8.6              187.99
50     Star Wars: Episode VII - The Force Awakens     8.1              936.63
54                                The Dark Knight     9.0              533.32
67                             Mad Max: Fury Road     8.1              153.63
74                                       Zootopia     8.1              341.26
76                                   The Avengers     8.1              623.28
77                           Inglourious Basterds     8.3              120.52
80                                      Inception     8.8              292.57
82                        The Wolf of Wall Street     8.2              116.87
83                                      Gone Girl     8.1              167.74
92                                       The Help     8.1              169.71
99                                   The Departed     8.5              132.37
114  Harry Potter and the Deathly Hallows: Part 2     8.1              380.96
124                         The Dark Knight Rises     8.5              448.13
138                                Shutter Island     8.1              127.97
144                              Django Unchained     8.4              162.80
241                                    Inside Out     8.2              356.45
427                          The Bourne Ultimatum     8.1              227.14
499                                            Up     8.3              292.98
634                                        WALL·E     8.4              223.81
645                                   Gran Torino     8.2              148.09
688                                   Toy Story 3     8.3              414.98
772                      How to Train Your Dragon     8.1              217.39

In [40]:
# Group movies by Director
# Calculate average Rating and Revenue for each director

director_summary = df.groupby("Director").agg({
    "Rating": "mean",
    "Revenue (Millions)": "mean"
})

# Display the result
print(director_summary)

                     Rating  Revenue (Millions)
Director
Aamir Khan             8.50              1.2000
Abdellatif Kechiche    7.80              2.2000
Adam Leon              6.50             47.9850
Adam McKay             7.00            109.5350
Adam Shankman          6.30             78.6650
...                     ...                 ...
Xavier Dolan           7.55             25.7375
Yimou Zhang            6.10             45.1300
Yorgos Lanthimos       7.20              4.4050
Zack Snyder            7.04            195.1480
Zackary Adler          5.10              6.5300

[644 rows x 2 columns]

In [42]:
# Group movies by Year
# Count number of movies
# Calculate average rating

year_summary = df.groupby("Year").agg(
    Movie_Count=("Title", "count"),
    Average_Rating=("Rating", "mean")
)

# Display the result
print(year_summary)

      Movie_Count  Average_Rating
Year
2006           44        7.125000
2007           53        7.133962
2008           52        6.784615
2009           51        6.960784
2010           60        6.826667
2011           63        6.838095
2012           64        6.925000
2013           91        6.812088
2014           98        6.837755
2015          127        6.602362
2016          297        6.436700

In [44]:
#Create a new Profitability column
# Profitability = Revenue / Duration

df["Profitability"] = (
    df["Revenue (Millions)"] / df["Runtime (Minutes)"]
)

# Display the result
df[[
    "Title",
    "Revenue (Millions)",
    "Runtime (Minutes)",
    "Profitability"
]].head()

,Title,Revenue (Millions),Runtime (Minutes),Profitability
0,Guardians of the Galaxy,333.13,121,2.753140
1,Prometheus,126.46,124,1.019839
2,Split,138.12,117,1.180513
3,Sing,270.32,108,2.502963
4,Suicide Squad,325.02,123,2.642439

In [46]:
# Sort movies by profitability
# and select the top 10

top_10_profitable = df.sort_values(
    by="Profitability",
    ascending=False
).head(10)

# Display the top 10
print(
    top_10_profitable[
        ["Title", "Profitability"]
    ]
)

                                          Title  Profitability
50   Star Wars: Episode VII - The Force Awakens       6.886985
85                               Jurassic World       5.259516
119                                Finding Dory       5.013299
87                                       Avatar       4.694506
76                                 The Avengers       4.358601
15                      The Secret Life of Pets       4.233448
688                                 Toy Story 3       4.028932
12                                    Rogue One       4.001278
174                                      Frozen       3.928824
797                             Despicable Me 2       3.755612

In [49]:
# Create a function to categorize movies based on rating

def rating_category(rating):

    # Rating below 6
    if rating < 6:
        return "Poor"

    # Rating from 6 to less than 7.5
    elif rating < 7.5:
        return "Average"

    # Rating 7.5 or above
    else:
        return "Excellent"

In [50]:
# Create a custom function to calculate movie score

def movie_score(row):

    # Calculate score using Rating and Revenue
    score = (
        row["Rating"] * 10
        + row["Revenue (Millions)"]
    )

    return score

In [52]:
# Apply the movie_score function to every row
df["Movie_Score"] = df.apply(
    movie_score,
    axis=1
)

# Display the result
df[[
    "Title",
    "Rating",
    "Revenue (Millions)",
    "Movie_Score"
]].head(10)

                     Title  Rating  Revenue (Millions)  Movie_Score
0  Guardians of the Galaxy     8.1             333.130      414.130
1               Prometheus     7.0             126.460      196.460
2                    Split     7.3             138.120      211.120
3                     Sing     7.2             270.320      342.320
4            Suicide Squad     6.2             325.020      387.020
5           The Great Wall     6.1              45.130      106.130
6               La La Land     8.3             151.060      234.060
7                 Mindhorn     6.4              47.985      111.985
8       The Lost City of Z     7.1               8.010       79.010
9               Passengers     7.0             100.010      170.010

In [53]:
# Display the first 10 rows with all newly created columns
df.head(10)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Genre_Count,Profitability,Movie_Score
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.130,76.0,1,2.753140,414.130
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.460,65.0,1,1.019839,196.460
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.120,62.0,1,1.180513,211.120
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.320,59.0,1,2.502963,342.320
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.020,40.0,1,2.642439,387.020
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.130,42.0,1,0.438155,106.130
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.060,93.0,1,1.180156,234.060
7,8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,47.985,71.0,1,0.539157,111.985
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.010,78.0,1,0.056809,79.010
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.010,41.0,1,0.862155,170.010

In [54]:
# Display all column names after completing the case study
print(df.columns)

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore', 'Genre_Count', 'Profitability', 'Movie_Score'],
      dtype='object')